apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: argocd
  labels:
    app: argocd
spec:
  type: NodePort
  selector: 
    app: app
  ports:
    - port: 5000
      targetPort: 5000