name: terraform Workflow

on:
  push:
    branches:
      - '**' # Triggers on all branches
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  init:
    name: Terraform init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{secrets.ID}}:role/github-action-openid
        role-session-name: githubactions
        aws-region: ${{secrets.REGION}}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: cd into main and run terraform init
      run: cd ./terraform_handson && terraform init -backend-config="bucket=${{secrets.BUCKET}}" -backend-config="key=${{secrets.KEY}}" -backend-config="region=${{secrets.REGION}}" -backend-config="encrypt=true"
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: terraform-init
        path: ./terraform_handson/

  validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{secrets.ID}}:role/github-action-openid
        role-session-name: githubactions
        aws-region: ${{secrets.REGION}}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: removed existing terraform files
      run: |
          rm -r ./terraform_handson
          ls -la

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: terraform-init


    - name: run terraform init
      run:  terraform init -backend-config="bucket=${{secrets.BUCKET}}" -backend-config="key=${{secrets.KEY}}" -backend-config="region=${{secrets.REGION}}" -backend-config="encrypt=true"
    
    - name: run terraform validate
      run:  terraform validate

