name: terraform Workflow

on:
  push:
    branches:
      - '**' # Triggers on all branches
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  terraform:
    name: Terraform init and validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{secrets.ID}}:role/github-action-openid
        role-session-name: githubactions
        aws-region: ${{secrets.REGION}}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: cd into main and run terraform init
      run: cd ./terraform_handson && terraform init -backend-config="bucket=${{secrets.BUCKET}}" -backend-config="key=${{secrets.KEY}}" -backend-config="region=${{secrets.REGION}}" -backend-config="encrypt=true"
    
    - name: cd into main and run terraform validate
      run: cd ./terraform_handson && terraform vaidate
